
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoyrvohtyjupmguyhbqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveXJ2b2h0eWp1cG1ndXloYnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNDUzMTgsImV4cCI6MjA4NDkyMTMxOH0.Wpav9mLvDsaMfU-kC2GR19N7hGoouWavQtxQmd4__3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: fetch.bind(globalThis),
    },
  }
);
